// <auto-generated />
using MaterialClient.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace MaterialClient.Common.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MaterialClientDbContext))]
    [Migration("20250127000000_AddSettingsEntity")]
    partial class AddSettingsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.Sqlite)
                .HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MaterialClient.Common.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraConfigsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentScannerConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlateRecognitionConfigsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScaleSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
