// <auto-generated />
using System;
using MaterialClient.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace MaterialClient.Common.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MaterialClientDbContext))]
    partial class MaterialClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.Sqlite)
                .HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MaterialClient.Common.Entities.AttachmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("AttachType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OssFullPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttachmentFiles", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.LicenseInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuthEndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("LicenseInfo", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LastEditUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEditor")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LowerLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UpperLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LastEditUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEditor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowerLimit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ProId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UpperLimit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CoId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeCode");

                    b.ToTable("MaterialTypes", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LastEditUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEditor")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitCalculationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MaterialUnits", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContectPhone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LastEditUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEditor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaterialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderTypeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraConfigsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentScannerConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlateRecognitionConfigsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScaleSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LicenseInfoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthEndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("FromProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LicenseInfoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.Waybill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbortReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<int?>("DeliveryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EarlyWarnType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEarlyWarn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoinTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModifierId");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaterialUnitRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OffsetRate")
                        .HasColumnType("TEXT");

                    b.Property<short>("OffsetResult")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OrderGoodsWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrderPcs")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrderPlanOnPcs")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrderPlanOnWeight")
                        .HasColumnType("TEXT");

                    b.Property<short>("OrderSource")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OrderTotalWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrderTruckWeight")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Waybills", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.WaybillAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WaybillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WaybillId", "AttachmentFileId")
                        .IsUnique();

                    b.ToTable("WaybillAttachments", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.WaybillMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoodsPcs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoodsPlanOnPcs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoodsPlanOnWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoodsTakeWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoodsWeight")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastEditUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEditor")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OffsetCount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OffsetRate")
                        .HasColumnType("TEXT");

                    b.Property<short>("OffsetResult")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OffsetWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WaybillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WaybillMaterials", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.WeighingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<int?>("DeliveryType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModifierId");

                    b.Property<long?>("MatchedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchedType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WaybillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeighingRecords", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.WeighingRecordAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WeighingRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeighingRecordId", "AttachmentFileId")
                        .IsUnique();

                    b.ToTable("WeighingRecordAttachments", (string)null);
                });

            modelBuilder.Entity("MaterialClient.Common.Entities.WorkSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MaterialTypeUpdatedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MaterialUpdatedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProviderUpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
