<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>MaterialClient.UI</RootNamespace>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Include="Backgrounds\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Irihi.Avalonia.Shared" />
        <PackageReference Include="Irihi.Ursa" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" />
        <PackageReference Include="MessageBox.Avalonia" />
        <PackageReference Include="ReactiveUI.SourceGenerators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Semi.Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MaterialClient.Common\MaterialClient.Common.csproj" />
    </ItemGroup>
</Project>
