using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using Avalonia.Threading;
using MaterialClient.Common.Entities;
using MaterialClient.Common.Entities.Enums;
using MaterialClient.Common.Services.Hardware;
using MaterialClient.Common.Services.Hikvision;
using ReactiveUI;
using Volo.Abp.Domain.Repositories;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MaterialClient.Common.Services;

namespace MaterialClient.ViewModels;

public partial class AttendedWeighingViewModel : ViewModelBase, IDisposable
{
    private readonly IRepository<WeighingRecord, long> _weighingRecordRepository;
    private readonly IRepository<Waybill, long> _waybillRepository;
    private readonly IServiceProvider _serviceProvider;
    private readonly ITruckScaleWeightService _truckScaleWeightService;
    private readonly MaterialClient.Common.Services.IAttendedWeighingService? _attendedWeighingService;
    private readonly CompositeDisposable _disposables = new();

    [ObservableProperty] private ObservableCollection<WeighingRecord> _unmatchedWeighingRecords = new();

    [ObservableProperty] private ObservableCollection<Waybill> _completedWaybills = new();

    [ObservableProperty] private WeighingRecord? _selectedWeighingRecord;

    [ObservableProperty] private Waybill? _selectedWaybill;

    [ObservableProperty] private ObservableCollection<string> _vehiclePhotos = new();

    [ObservableProperty] private string? _billPhotoPath;

    [ObservableProperty] private DateTime _currentTime = DateTime.Now;

    [ObservableProperty] private decimal _currentWeight;

    [ObservableProperty] private bool _isReceiving = true;

    [ObservableProperty] private bool _isShowAllRecords = true;

    [ObservableProperty] private bool _isShowUnmatched;

    [ObservableProperty] private bool _isShowCompleted;

    [ObservableProperty] private ObservableCollection<object> _displayRecords = new();

    [ObservableProperty] private object? _selectedRecord;

    [ObservableProperty] private string? _currentEntryPhoto1;

    [ObservableProperty] private string? _currentEntryPhoto2;

    [ObservableProperty] private string? _currentEntryPhoto3;

    [ObservableProperty] private string? _currentEntryPhoto4;

    [ObservableProperty] private string? _entryPhoto1;

    [ObservableProperty] private string? _entryPhoto2;

    [ObservableProperty] private string? _entryPhoto3;

    [ObservableProperty] private string? _entryPhoto4;

    [ObservableProperty] private string? _exitPhoto1;

    [ObservableProperty] private string? _exitPhoto2;

    [ObservableProperty] private string? _exitPhoto3;

    [ObservableProperty] private string? _exitPhoto4;

    [ObservableProperty] private string? _materialInfo;

    [ObservableProperty] private string? _offsetInfo;

    [ObservableProperty] private bool _isScaleOnline;

    [ObservableProperty] private bool _isCameraOnline;

    [ObservableProperty] private string? _mostFrequentPlateNumber;

    private AttendedWeighingStatus _currentWeighingStatus = AttendedWeighingStatus.OffScale;

    /// <summary>
    /// 当前称重状态的中文文本
    /// </summary>
    public string CurrentWeighingStatusText => GetStatusText(_currentWeighingStatus);

    public bool IsWeighingRecordSelected => SelectedWeighingRecord != null && SelectedWaybill == null;
    public bool IsWaybillSelected => SelectedWaybill != null && SelectedWeighingRecord == null;

    private Timer? _autoRefreshTimer;
    private const int AutoRefreshIntervalMs = 5000; // Refresh every 5 seconds

    public AttendedWeighingViewModel(
        IRepository<WeighingRecord, long> weighingRecordRepository,
        IRepository<Waybill, long> waybillRepository,
        IServiceProvider serviceProvider,
        ITruckScaleWeightService truckScaleWeightService,
        IAttendedWeighingService attendedWeighingService
    )
    {
        _weighingRecordRepository = weighingRecordRepository;
        _waybillRepository = waybillRepository;
        _serviceProvider = serviceProvider;
        _truckScaleWeightService = truckScaleWeightService;
        _attendedWeighingService = attendedWeighingService;


        // Commands are now generated by [RelayCommand] attributes

        // Subscribe to SelectedWeighingRecord changes
        this.WhenAnyValue(x => x.SelectedWeighingRecord)
            .Subscribe(HandleSelectedWeighingRecordChanged);

        // Subscribe to SelectedWaybill changes
        this.WhenAnyValue(x => x.SelectedWaybill)
            .Subscribe(HandleSelectedWaybillChanged);

        // Subscribe to display mode changes to update IsWeighingRecordSelected and IsWaybillSelected
        this.WhenAnyValue(
                x => x.SelectedWeighingRecord,
                x => x.SelectedWaybill,
                (record, waybill) => (record, waybill))
            .Subscribe(_ =>
            {
                this.RaisePropertyChanged(nameof(IsWeighingRecordSelected));
                this.RaisePropertyChanged(nameof(IsWaybillSelected));
            });

        // Load initial data
        _ = RefreshAsync();

        // Start auto-refresh timer to reflect matching results in real-time
        StartAutoRefresh();
        StartTimeUpdateTimer();

        // Subscribe to weight updates from truck scale
        _truckScaleWeightService.WeightUpdates
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe(weight => { CurrentWeight = weight; })
            .DisposeWith(_disposables);

        // Start timer to check scale online status periodically
        StartScaleStatusCheckTimer();

        // Start timer to check camera online status periodically
        StartCameraStatusCheckTimer();

        // Start all devices when ViewModel is created
        _ = StartAllDevicesAsync();

        // Start ReactiveUI observable to update most frequent plate number
        StartPlateNumberObservable();

        // Start ReactiveUI observable to update weighing status
        StartStatusObservable();
    }

    /// <summary>
    /// Start all devices
    /// </summary>
    private async Task StartAllDevicesAsync()
    {
        try
        {
            var deviceManagerService =
                _serviceProvider.GetRequiredService<MaterialClient.Common.Services.IDeviceManagerService>();
            await deviceManagerService.StartAsync();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error starting devices: {ex.Message}");
        }
    }

    /// <summary>
    /// Start timer to periodically check scale online status
    /// </summary>
    private void StartScaleStatusCheckTimer()
    {
        var statusTimer = new Timer(_ =>
        {
            try
            {
                // Timer callback runs on thread pool, check status on background thread
                var isOnline = _truckScaleWeightService.IsOnline;

                // Update property on UI thread to avoid blocking
                Dispatcher.UIThread.Post(() => { IsScaleOnline = isOnline; });
            }
            catch
            {
                // Update property on UI thread
                Dispatcher.UIThread.Post(() => { IsScaleOnline = false; });
            }
        }, null, TimeSpan.Zero, TimeSpan.FromSeconds(2)); // Check every 2 seconds

        _disposables.Add(statusTimer);
    }

    /// <summary>
    /// Start timer to periodically check camera online status
    /// </summary>
    private void StartCameraStatusCheckTimer()
    {
        var statusTimer = new Timer(_ =>
        {
            // Timer callback runs on thread pool, execute async check without blocking
            _ = Task.Run(async () =>
            {
                try
                {
                    await CheckCameraOnlineStatusAsync();
                }
                catch
                {
                    // Update property on UI thread
                    Dispatcher.UIThread.Post(() => { IsCameraOnline = false; });
                }
            });
        }, null, TimeSpan.Zero, TimeSpan.FromSeconds(5)); // Check every 5 seconds

        _disposables.Add(statusTimer);
    }

    /// <summary>
    /// Check camera online status
    /// </summary>
    private async Task CheckCameraOnlineStatusAsync()
    {
        try
        {
            var settingsService =
                _serviceProvider.GetRequiredService<MaterialClient.Common.Services.ISettingsService>();
            var hikvisionService = _serviceProvider.GetRequiredService<IHikvisionService>();
            var settings = await settingsService.GetSettingsAsync();
            var cameraConfigs = settings.CameraConfigs;

            if (cameraConfigs.Count == 0)
            {
                // Update property on UI thread
                Dispatcher.UIThread.Post(() => { IsCameraOnline = false; });
                return;
            }

            // Check if at least one camera is online
            bool anyOnline = false;
            foreach (var cameraConfig in cameraConfigs)
            {
                if (string.IsNullOrWhiteSpace(cameraConfig.Ip) ||
                    string.IsNullOrWhiteSpace(cameraConfig.Port) ||
                    string.IsNullOrWhiteSpace(cameraConfig.UserName) ||
                    string.IsNullOrWhiteSpace(cameraConfig.Password))
                {
                    continue;
                }

                if (!int.TryParse(cameraConfig.Port, out var port))
                {
                    continue;
                }

                var hikvisionConfig = new HikvisionDeviceConfig
                {
                    Ip = cameraConfig.Ip,
                    Port = port,
                    Username = cameraConfig.UserName,
                    Password = cameraConfig.Password
                };

                var isOnline = await Task.Run(() => hikvisionService.IsOnline(hikvisionConfig));
                if (isOnline)
                {
                    anyOnline = true;
                    break; // At least one camera is online
                }
            }

            // Update property on UI thread
            Dispatcher.UIThread.Post(() => { IsCameraOnline = anyOnline; });
        }
        catch
        {
            // Update property on UI thread
            Dispatcher.UIThread.Post(() => { IsCameraOnline = false; });
        }
    }


    /// <summary>
    /// Cleanup resources
    /// </summary>
    public void Dispose()
    {
        _disposables.Dispose();
        _autoRefreshTimer?.Dispose();
    }

    [RelayCommand]
    private async Task RefreshAsync()
    {
        try
        {
            // Load unmatched weighing records (RecordType == Unmatch)
            var allRecords = await _weighingRecordRepository.GetListAsync();
            var unmatchedRecords = allRecords
                .Where(x => x.MatchedId == null)
                .OrderByDescending(r => r.CreationTime)
                .ToList();

            UnmatchedWeighingRecords.Clear();
            foreach (var record in unmatchedRecords)
            {
                UnmatchedWeighingRecords.Add(record);
            }

            // Load completed waybills
            var allWaybills = await _waybillRepository.GetListAsync();
            var waybills = allWaybills
                .OrderByDescending(w => w.CreationTime)
                .ToList();

            CompletedWaybills.Clear();
            foreach (var waybill in waybills)
            {
                CompletedWaybills.Add(waybill);
            }

            // Update display records after refresh
            UpdateDisplayRecords();
        }
        catch
        {
            // If repositories are not available, collections will remain empty
            // This allows the UI to work even before ABP is fully initialized
        }
    }

    [RelayCommand]
    private void SetReceiving()
    {
        IsReceiving = true;
    }

    [RelayCommand]
    private void SetSending()
    {
        IsReceiving = false;
    }

    [RelayCommand]
    private void ShowAllRecords()
    {
        SetDisplayMode(0);
    }

    [RelayCommand]
    private void ShowUnmatched()
    {
        SetDisplayMode(1);
    }

    [RelayCommand]
    private void ShowCompleted()
    {
        SetDisplayMode(2);
    }

    [RelayCommand]
    private void SelectRecord(object? record)
    {
        SelectedRecord = record;
        // TODO: Load photos for the selected record
    }

    [RelayCommand]
    private void TakeBillPhoto()
    {
        // TODO: Implement bill photo capture
    }

    [RelayCommand]
    private void Save()
    {
        // TODO: Implement save logic
    }

    [RelayCommand]
    private void Close()
    {
        // TODO: Implement close logic
    }

    [RelayCommand]
    private void OpenSettings()
    {
        try
        {
            var settingsWindow = _serviceProvider.GetRequiredService<Views.SettingsWindow>();
            settingsWindow.Show();
        }
        catch
        {
            // Handle error opening settings window
        }
    }

    private void SetDisplayMode(int mode)
    {
        IsShowAllRecords = mode == 0;
        IsShowUnmatched = mode == 1;
        IsShowCompleted = mode == 2;
        OnPropertyChanged(nameof(IsShowAllRecords));
        OnPropertyChanged(nameof(ShowUnmatched));
        OnPropertyChanged(nameof(ShowCompleted));
        UpdateDisplayRecords();
    }

    private void UpdateDisplayRecords()
    {
        DisplayRecords.Clear();

        if (IsShowAllRecords)
        {
            foreach (var record in UnmatchedWeighingRecords)
            {
                DisplayRecords.Add(record);
            }

            foreach (var waybill in CompletedWaybills)
            {
                DisplayRecords.Add(waybill);
            }
        }
        else if (IsShowUnmatched)
        {
            foreach (var record in UnmatchedWeighingRecords)
            {
                DisplayRecords.Add(record);
            }
        }
        else if (IsShowCompleted)
        {
            foreach (var waybill in CompletedWaybills)
            {
                DisplayRecords.Add(waybill);
            }
        }
    }

    private void StartTimeUpdateTimer()
    {
        var timeTimer = new Timer(_ => CurrentTime = DateTime.Now, null,
            TimeSpan.Zero, TimeSpan.FromSeconds(1));
    }

    private void StartAutoRefresh()
    {
        _autoRefreshTimer = new Timer(async _ => await RefreshAsync(), null,
            TimeSpan.FromMilliseconds(AutoRefreshIntervalMs),
            TimeSpan.FromMilliseconds(AutoRefreshIntervalMs));
    }

    public void StopAutoRefresh()
    {
        _autoRefreshTimer?.Dispose();
        _autoRefreshTimer = null;
    }

    /// <summary>
    /// Start ReactiveUI observable to update most frequent plate number
    /// </summary>
    private void StartPlateNumberObservable()
    {
        if (_attendedWeighingService == null)
        {
            return;
        }

        // Subscribe to plate number changes from service
        _attendedWeighingService.MostFrequentPlateNumberChanges
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe(plateNumber => { MostFrequentPlateNumber = plateNumber; })
            .DisposeWith(_disposables);
    }

    /// <summary>
    /// Start ReactiveUI observable to update weighing status
    /// </summary>
    private void StartStatusObservable()
    {
        if (_attendedWeighingService == null)
        {
            return;
        }

        // Subscribe to status changes from service
        _attendedWeighingService.StatusChanges
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe(status =>
            {
                _currentWeighingStatus = status;
                OnPropertyChanged(nameof(CurrentWeighingStatusText));
            })
            .DisposeWith(_disposables);
    }

    /// <summary>
    /// 获取状态的中文文本
    /// </summary>
    private static string GetStatusText(AttendedWeighingStatus status)
    {
        return status switch
        {
            AttendedWeighingStatus.OffScale => "预重已结束",
            AttendedWeighingStatus.WaitingForStability => "等待稳定",
            AttendedWeighingStatus.WeightStabilized => "重量已稳定",
            _ => "未知状态"
        };
    }

    private void HandleSelectedWeighingRecordChanged(WeighingRecord? value)
    {
        // Clear waybill selection when weighing record is selected
        if (value != null)
        {
            SelectedWaybill = null;
            _ = LoadWeighingRecordPhotos(value);
        }
        else
        {
            VehiclePhotos.Clear();
            BillPhotoPath = null;
        }

        this.RaisePropertyChanged(nameof(IsWeighingRecordSelected));
        this.RaisePropertyChanged(nameof(IsWaybillSelected));
    }

    private void HandleSelectedWaybillChanged(Waybill? value)
    {
        // Clear weighing record selection when waybill is selected
        if (value != null)
        {
            SelectedWeighingRecord = null;
            _ = LoadWaybillPhotos(value);
        }
        else
        {
            VehiclePhotos.Clear();
            BillPhotoPath = null;
        }

        this.RaisePropertyChanged(nameof(IsWeighingRecordSelected));
        this.RaisePropertyChanged(nameof(IsWaybillSelected));
    }

    private async Task LoadWeighingRecordPhotos(WeighingRecord record)
    {
        try
        {
            var attachmentRepository = _serviceProvider.GetService<IRepository<WeighingRecordAttachment, int>>();
            if (attachmentRepository != null)
            {
                var attachments = await attachmentRepository.GetListAsync(
                    predicate: x => x.WeighingRecordId == record.Id,
                    includeDetails: true
                );

                VehiclePhotos.Clear();
                BillPhotoPath = null;

                foreach (var attachment in attachments)
                {
                    if (attachment.AttachmentFile != null && !string.IsNullOrEmpty(attachment.AttachmentFile.LocalPath))
                    {
                        // Determine if attachment is vehicle photo or bill photo based on AttachType
                        if (attachment.AttachmentFile.AttachType == AttachType.EntryPhoto ||
                            attachment.AttachmentFile.AttachType == AttachType.ExitPhoto)
                        {
                            VehiclePhotos.Add(attachment.AttachmentFile.LocalPath);
                        }
                        else if (attachment.AttachmentFile.AttachType == AttachType.TicketPhoto)
                        {
                            BillPhotoPath = attachment.AttachmentFile.LocalPath;
                        }
                    }
                }
            }
        }
        catch
        {
            // If repository is not available, photos will remain empty
        }
    }

    private async Task LoadWaybillPhotos(Waybill waybill)
    {
        try
        {
            var waybillAttachmentRepository = _serviceProvider.GetService<IRepository<WaybillAttachment, int>>();
            if (waybillAttachmentRepository != null)
            {
                var attachments = await waybillAttachmentRepository.GetListAsync(
                    predicate: x => x.WaybillId == waybill.Id,
                    includeDetails: true
                );

                VehiclePhotos.Clear();
                BillPhotoPath = null;

                foreach (var attachment in attachments)
                {
                    if (attachment.AttachmentFile != null && !string.IsNullOrEmpty(attachment.AttachmentFile.LocalPath))
                    {
                        // Determine if attachment is vehicle photo or bill photo based on AttachType
                        if (attachment.AttachmentFile.AttachType == AttachType.EntryPhoto ||
                            attachment.AttachmentFile.AttachType == AttachType.ExitPhoto)
                        {
                            VehiclePhotos.Add(attachment.AttachmentFile.LocalPath);
                        }
                        else if (attachment.AttachmentFile.AttachType == AttachType.TicketPhoto)
                        {
                            BillPhotoPath = attachment.AttachmentFile.LocalPath;
                        }
                    }
                }
            }
        }
        catch
        {
            // If repository is not available, photos will remain empty
        }
    }
}